//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RGUI.Resources.str", typeof(str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа такая программа.
        /// </summary>
        public static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha:.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окрестность.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0.
        /// </summary>
        public static string C0 {
            get {
                return ResourceManager.GetString("C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        public static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление сходимости....
        /// </summary>
        public static string ConvergenseDirection {
            get {
                return ResourceManager.GetString("ConvergenseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость сходимости....
        /// </summary>
        public static string ConvergenseSpeed {
            get {
                return ResourceManager.GetString("ConvergenseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрасить сцену.
        /// </summary>
        public static string FillScene {
            get {
                return ResourceManager.GetString("FillScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямой итерацией.
        /// </summary>
        public static string FillSceneDirect {
            get {
                return ResourceManager.GetString("FillSceneDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратной итерацией.
        /// </summary>
        public static string FillSceneReverse {
            get {
                return ResourceManager.GetString("FillSceneReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение как....
        /// </summary>
        public static string ImageAs {
            get {
                return ResourceManager.GetString("ImageAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация.
        /// </summary>
        public static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая итерация.
        /// </summary>
        public static string IterateDirect {
            get {
                return ResourceManager.GetString("IterateDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная итерация.
        /// </summary>
        public static string IterateReverse {
            get {
                return ResourceManager.GetString("IterateReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итерирование.
        /// </summary>
        public static string Iterating {
            get {
                return ResourceManager.GetString("Iterating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итераций:.
        /// </summary>
        public static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окрестность точки.
        /// </summary>
        public static string PointArea {
            get {
                return ResourceManager.GetString("PointArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать точку вручную.
        /// </summary>
        public static string SelectManually {
            get {
                return ResourceManager.GetString("SelectManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разбить на полуплоскости.
        /// </summary>
        public static string SplitToHalhPlains {
            get {
                return ResourceManager.GetString("SplitToHalhPlains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трассировать....
        /// </summary>
        public static string ToTrack {
            get {
                return ResourceManager.GetString("ToTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трассировать прямую итерацию....
        /// </summary>
        public static string ToTrackDirect {
            get {
                return ResourceManager.GetString("ToTrackDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трассировать обратную итерацию....
        /// </summary>
        public static string ToTrackReverse {
            get {
                return ResourceManager.GetString("ToTrackReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличение.
        /// </summary>
        public static string Zooming {
            get {
                return ResourceManager.GetString("Zooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
